# Generated by Django 4.2.9 on 2026-04-04 18:49

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = []

    operations = [
        migrations.CreateModel(
            name="Certificate",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("name", models.CharField(max_length=200)),
                ("issuer", models.CharField(blank=True, max_length=200)),
                ("date", models.CharField(blank=True, max_length=20)),
                ("url", models.CharField(blank=True, max_length=300)),
                ("order", models.IntegerField(default=0)),
            ],
            options={
                "ordering": ["order"],
            },
        ),
        migrations.CreateModel(
            name="CV",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("title", models.CharField(default="Mening CV", max_length=150)),
                (
                    "template",
                    models.CharField(
                        choices=[
                            ("modern", "Modern"),
                            ("classic", "Classic"),
                            ("creative", "Creative"),
                        ],
                        default="modern",
                        max_length=50,
                    ),
                ),
                ("first_name", models.CharField(max_length=100)),
                ("last_name", models.CharField(max_length=100)),
                ("profession", models.CharField(blank=True, max_length=150)),
                ("email", models.EmailField(max_length=254)),
                ("phone", models.CharField(max_length=25)),
                ("address", models.CharField(blank=True, max_length=200)),
                ("website", models.CharField(blank=True, max_length=200)),
                ("linkedin", models.CharField(blank=True, max_length=200)),
                ("github", models.CharField(blank=True, max_length=200)),
                (
                    "photo",
                    models.ImageField(blank=True, null=True, upload_to="cv_photos/"),
                ),
                ("summary", models.TextField(blank=True)),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
            ],
            options={
                "ordering": ["-updated_at"],
            },
        ),
        migrations.CreateModel(
            name="Skill",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("name", models.CharField(max_length=100)),
                (
                    "level",
                    models.IntegerField(
                        choices=[
                            (1, "Boshlang'ich"),
                            (2, "O'rta-past"),
                            (3, "O'rta"),
                            (4, "Yuqori"),
                            (5, "Ekspert"),
                        ],
                        default=3,
                    ),
                ),
                ("category", models.CharField(blank=True, max_length=100)),
                ("order", models.IntegerField(default=0)),
                (
                    "cv",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="skills",
                        to="cv.cv",
                    ),
                ),
            ],
            options={
                "ordering": ["order", "name"],
            },
        ),
        migrations.CreateModel(
            name="Language",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("name", models.CharField(max_length=100)),
                (
                    "level",
                    models.CharField(
                        choices=[
                            ("A1", "A1 - Boshlang'ich"),
                            ("A2", "A2 - Elementar"),
                            ("B1", "B1 - O'rta"),
                            ("B2", "B2 - O'rta-yuqori"),
                            ("C1", "C1 - Yuqori"),
                            ("C2", "C2 - Professional"),
                            ("native", "Ona tili"),
                        ],
                        default="B1",
                        max_length=10,
                    ),
                ),
                ("order", models.IntegerField(default=0)),
                (
                    "cv",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="languages",
                        to="cv.cv",
                    ),
                ),
            ],
            options={
                "ordering": ["order"],
            },
        ),
        migrations.CreateModel(
            name="Experience",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("company", models.CharField(max_length=200)),
                ("position", models.CharField(max_length=200)),
                ("location", models.CharField(blank=True, max_length=200)),
                ("start_date", models.CharField(max_length=20)),
                ("end_date", models.CharField(blank=True, max_length=20)),
                ("is_current", models.BooleanField(default=False)),
                ("description", models.TextField(blank=True)),
                ("order", models.IntegerField(default=0)),
                (
                    "cv",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="experiences",
                        to="cv.cv",
                    ),
                ),
            ],
            options={
                "ordering": ["order", "-start_date"],
            },
        ),
        migrations.CreateModel(
            name="Education",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("institution", models.CharField(max_length=200)),
                ("degree", models.CharField(max_length=200)),
                ("field", models.CharField(blank=True, max_length=200)),
                ("start_date", models.CharField(max_length=20)),
                ("end_date", models.CharField(blank=True, max_length=20)),
                ("is_current", models.BooleanField(default=False)),
                ("gpa", models.CharField(blank=True, max_length=20)),
                ("description", models.TextField(blank=True)),
                ("order", models.IntegerField(default=0)),
                (
                    "cv",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="educations",
                        to="cv.cv",
                    ),
                ),
            ],
            options={
                "ordering": ["order", "-start_date"],
            },
        ),
    ]
